### ISSUE TITLE
Unable to Hit Login Page for Peer Resetting Issue

### ISSUE THREAD

**Issue by rKalb** [cseelye/pykevoplus#4]
requests.get("https://mykevo.com/login")
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-72ebce34b22d>", line 1, in <module>
    requests.get("https://mykevo.com/login")
  File "/Library/Python/2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))

**Comment by cseelye** [comment]
I've typically seen this type of error when something is wrong with the ssl setup on your machine, usually too old of a version. Try things like pulling in a newer requests, which should also upgrade pyopenssl -

pip install --upgrade requests[security]

If you are using a virtualenv, you can also try upgrading virtualenv/virtualenvwrapper and recreating your env.
